lavalink:
  plugins:
  - dependency: dev.lavalink.youtube:youtube-plugin:1.13.3
    repository: https://maven.lavalink.dev/releases
  server:
    bufferDurationMs: 400
    frameBufferDurationMs: 1000
    gc-warnings: true
    password: youshallnotpass
    playerUpdateInterval: 1
    soundcloudSearchEnabled: true
    sources:
      bandcamp: true
      http: true
      local: true
      soundcloud: true
      twitch: true
      vimeo: true
      youtube: false
    youtubePlaylistLoadLimit: 100
    youtubeSearchEnabled: true
logging:
  file:
    path: ./logs/
  level:
    lavalink: INFO
    root: INFO
  logback:
    rollingpolicy:
      max-history: 15
      max-size: 10MB
metrics:
  prometheus:
    enabled: false
    endpoint: /metrics
plugins:
  youtube:
    clients:
      - MUSIC
      - WEB
      - WEBEMBEDDED
      - ANDROID_TESTSUITE
      - TVHTML5EMBEDDED
      - MEDIA_CONNECT
      - IOS
    enabled: true
    TVHTML5EMBEDDED:
      playlistLoading: false
      searching: false
      videoLoading: false
    WEB:
      playback: true
      allowDirectPlaylistIds: true
      allowDirectVideoIds: true
      allowSearch: true
sentry:
  dsn: ''
  environment: ''
server:
  address: 0.0.0.0
  port: 2333
