server:
  host: "localhost"
  port: 2333 #port
lavalink:
  server:
    password: "youshallnotpass"
    sources:
      youtube: true
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      mixer: true
      http: true
      local: true
    sentryDsn: ""
    bufferDurationMs: 400
    youtubePlaylistLoadLimit: 10000
    youtubeConfig:
      email: "temelcearazvan@gmail.com"
      password: "xwid bsyz ktkk eeuo"
logging:
  file:
    max-history: 7
    max-size: 1GB
  path: ./logs/
  level:
    root: INFO
    lavalink: INFO

